version: '3.10'
services:

  lab_1:
    container_name: lab_1
    build:
      context: ./lab_1
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    networks:
      - backend_3
    restart: always

  lab_2:
    container_name: lab_2
    build:
      context: ./lab_2
    env_file: .env
    restart: always
    ports:
      - "8001:8001"
    command: uvicorn main:app --host 0.0.0.0 --port 8001
    depends_on:
      - redis
      - db
    networks:
      - backend_3

  celery:
    build:
      context: ./lab_2
    container_name: celery
    command: celery -A celery_start worker --loglevel=info
    restart: always
    depends_on:
      - redis
      - lab_2
      - db
    networks:
      - backend_3

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - backend_3
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=Bakugan102!
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - backend_3


volumes:
  postgres_data:

networks:
  backend_3:
     driver: bridge